### PR TITLE
Fix the broken SED-ML element 

### PR DESCRIPTION
**Pull request by gmarupilla**
- [x] Remove duplicate declaration from SED-ML top level element

### CODE REVIEW

**Review by jonrkarr — COMMENTED** [review]
Are you intending for the test suite to include two cases involving the Vilar model?

**Comment by gmarupilla** [comment]
Yes, Ion suggested attaching a deterministic and stochastic VILAR model for the test suite.

**Comment by jonrkarr** [comment]
The original OMEX file had both deterministic simulations of the Vilar model. Are you trying to split this into separate test cases?

I'm trying to understand what you're trying to do because the README and example simulations for the dispatch app also need to be updated.

**Comment by gmarupilla** [comment]
I believe Ion's motivation is to see if the test case is failing/passing just for stochastic, just for deterministic, or both?
Because if we test with the archive with all kinds of simulation, and it fails, we will have to check the internal detailed logs (which might not be accessible through GH actions) to see the test failed because of deterministic simulation or stochastic simulation. 

And Yes, in that scenario we will have to create separate test cases (in the test suite) for that. This is what I understood. @moraru  can you please confirm?

**Comment by jonrkarr** [comment]
I fixed the namespaces for the Villar example. 

I created two copies of the Villar example -- one with the deterministic tasks and one with the stochastic tasks.

I added reports (i.e. `<sedml:Report>`) to the combine deterministic/stochastic Villar example and to the individual deterdeterministicminstic and stochastic examples.

I also corrected the model references in the Villar examples. VCell should have failed on these examples. It didn't because VCell doesn't appear to support model resolution via URL fragments as intended in the SED-ML specifications. I brought this up last month in biosimulators/Biosimulators_VCell#50.

I confirmed that the new files all execute with VCell 7.3.0.07 and other simulators (except VCell 7.3.0.07 ignores SED reports).

VCell 7.3.0.13 appears to have other issues. See biosimulators/Biosimulators_VCell#60.

**Comment by jonrkarr** [comment]
I also needed to make the reactions irreversible for the stochastic example so that COPASI could also simulate this example.

**Pull request closed without merging**
